version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    environment:
      - PYTHONUNBUFFERED=1

  agent:
    build: ./agent
    depends_on:
      - backend
      - kafka
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
